homework
Daniluko/OfficeApp pull request #1
Opened 2019-03-25 01:41 UTC by Daniluko

2019-03-25 10:21 UTC, SerhiiPasko requested changes
Read comment

2019-03-25 10:21 UTC, SergeyPasko commented on src/test/java/project/springData/service/OfficesServiceImplTest.java
> +    public void testInsertOffice() {
Tests not full. You also must test when , in this case, office already exist

2019-03-25 10:44 UTC, Yanetta commented on src/main/java/project/controller/OfficeController.java
> +    public @ResponseBody
Does this response have body?

2019-03-26 08:41 UTC, SerhiiPasko approved these changes
Good

2019-03-26 17:19 UTC, merged